# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9877c1fc68ffea7c5b0d192714f0bbb8a0148b73fb72591c95db0a494d7654a717615b3a0ccba530772d002bb852e3ca466c0a831a9fe0cfa55dc16631cb928

test:
  secret_key_base: b4674f9b3a9fd96c348ecd259ff567a7a2daa946ede2f4ee5ef3013080c7b5d9954e69cfe1e71f2ad755695076dba4380025dec630395673b2edf7fc38636df7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
